# To train the Object detection Model:

In [ ]:
from ultralytics import YOLO

# # Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# # Train the model with 2 GPUs
results = model.train(data='data.yaml', epochs=200, imgsz=640) 


# Test Object Detection Model:

In [1]:
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('ultralytics/runs/detect/train_model/weights/best.pt')

# Run inference on 'bus.jpg' with arguments
model.predict('test_vid.mp4', save=True, imgsz=320, conf=0.2)


Ultralytics YOLOv8.0.3  Python-3.9.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 1 licence, 65.0ms
video 1/1 (2/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 1 licence, 7.0ms
video 1/1 (3/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 1 licence, 5.1ms
video 1/1 (4/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 1 licence, 6.0ms
video 1/1 (5/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 1 licence, 5.0ms
video 1/1 (6/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 1 licence, 5.0ms
video 1/1 (7/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 192x320 5.0ms
video 1/1 (8/672) D:\yolov8_lic

[tensor([[6.53000e+02, 3.20000e+02, 1.28600e+03, 5.02000e+02, 3.94287e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[6.52000e+02, 3.20000e+02, 1.28700e+03, 5.02000e+02, 4.22607e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[6.52000e+02, 3.20000e+02, 1.28700e+03, 5.02000e+02, 4.26270e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[6.52000e+02, 3.20000e+02, 1.28700e+03, 5.02000e+02, 4.24316e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[6.53000e+02, 3.20000e+02, 1.28600e+03, 5.02000e+02, 4.32129e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[6.54000e+02, 3.20000e+02, 1.28700e+03, 5.02000e+02, 4.32129e-01, 0.00000e+00]], device='cuda:0'),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor([], device='cuda:0', size=(0, 6)),
 tensor(

# Recognize License plate after Detecting  using easy-ocr

In [1]:
#!pip install easyocr

In [ ]:
!python predict_modified.py model='ultralytics/runs/detect/train_model/weights/best.pt' source='test_vid.mp4'

Ultralytics YOLOv8.0.3  Python-3.9.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
Fusing layers... 
Model summary: 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
video 1/1 (1/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 47.0ms
video 1/1 (2/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (3/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (4/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (5/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 13.0ms
video 1/1 (6/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 9.0ms
video 1/1 (7/672) D:\yolov8_license_plate_recog\License_plate_recognition\test_vid.mp4: 384x640 1 licence, 10.0ms
video 1/1 (8/67

In [1]:
!python predict_modified.py model='ultralytics/runs/detect/train_model/weights/best.pt' source='mycarplate.mp4' 

Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
2025-02-25 18:10:08.001774: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-25 18:10:09.410809: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Ultralytics YOLOv8.0.3  Python-3.9.13 torch-2.5.0+cu118 CPU
c:\Visual Studio codes\Automatic-Number-Plate-Recognition--ANPR-\ultralytics\nn\tasks.py:303: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possi

In [1]:
!python predict_modified.py model='ultralytics/runs/detect/train_model/weights/best.pt' source='mycarplate.mp4' 

Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
2025-02-25 18:43:05.057507: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-25 18:43:08.000502: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Ultralytics YOLOv8.0.3  Python-3.9.13 torch-2.5.0+cu118 CPU
c:\Visual Studio codes\Number_Plate_Recog\ultralytics\nn\tasks.py:303: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malici